# Generated by Django 3.2.8 on 2022-09-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_skills_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_telegram',
            new_name='social_twitter',
        ),
    ]
