# Generated by Django 4.0.6 on 2022-10-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_massage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Massage',
            new_name='Message',
        ),
    ]
