# Generated by Django 4.0 on 2023-02-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_massage_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
    ]
